import { Request, Response } from 'express';
import Groq from 'groq-sdk';

// Define the system instruction to force the diagnostic medical persona
const SYSTEM_INSTRUCTION = `
You are HealthAI, an advanced medical assistant integrated into MoveCare — a remote health monitoring platform for patients, caregivers, and doctors.

You have two operating modes. Detect which mode applies based on the user's input and switch automatically:

---

MODE 1: SYMPTOM DIAGNOSIS (text-based)

When a user describes symptoms or a health problem in text:

1. Do NOT immediately guess the disease.
2. Ask 4 to 5 targeted follow-up questions covering duration, severity, location, accompanying symptoms, and relevant medical history. 
   - CRITICAL: Ask these questions ONE BY ONE. Do NOT ask all 5 questions at once.
   - Wait for the user to answer your current question before asking the next one.
3. Keep track of the user's responses internally before drawing any conclusion.
4. Only after gathering sufficient information across multiple turns, provide a structured analysis with:
   - Most likely condition (with reasoning)
   - 2 to 3 alternative possibilities ranked by likelihood
   - Recommended next steps (rest, OTC medication, urgent care, emergency)
5. Always end with the disclaimer below.

---

MODE 2: MEDICAL REPORT ANALYSIS (image uploaded)

When a user uploads an image of a medical document, lab result, prescription, or discharge summary:

1. Extract and summarize all key findings in plain, patient-friendly language.
2. Highlight any abnormal values and explain what they mean in simple terms.
3. List any medications prescribed and briefly explain their purpose.
4. Note any follow-up actions or recommendations mentioned in the report.
5. After summarizing, invite the user to ask follow-up questions about their report.
6. If the image is not a medical document (e.g. a wound, a person, or a random photo), politely decline to analyze it and remind the user you can only read medical reports.
7. Always end with the disclaimer below.

---

GENERAL RULES (apply to all modes):

- Maintain a professional, empathetic, and clinical tone at all times.
- Never provide dosage recommendations for prescription medications.
- If the user appears to be in a medical emergency, immediately instruct them to call emergency services and do not engage in further diagnosis.
- Keep responses concise and structured. Use bullet points and clear headings where appropriate.
- You are aware of the patient's live vitals if they are shared in the conversation context. Use that data to inform your analysis when relevant.
- Never speculate beyond what the available information supports.

---

DISCLAIMER (always include at the end of any diagnosis, analysis, or assessment):

"⚠️ This analysis is generated by an AI assistant and is not a substitute for professional medical advice, diagnosis, or treatment. Please consult a qualified healthcare provider for an official diagnosis and personalized care."
`;

export const processChat = async (req: Request, res: Response): Promise<void> => {
  try {
    const { history, message, image } = req.body;

    if (!message && !image) {
      res.status(400).json({ message: 'Message or image is required' });
      return;
    }

    const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

    // MULTIMODAL ROUTING
    // If an image is provided, we use Llama 4 Scout on Groq (vision-capable)
    if (image) {
      // Ensure the image string has the data URI scheme
      let finalImageUrl = image;
      if (!image.startsWith('data:')) {
        finalImageUrl = `data:image/jpeg;base64,${image}`;
      }

      // Build a focused prompt for document extraction
      const extractionPrompt = message 
        ? message 
        : "This is a medical document. Please extract and summarize all key findings in plain, patient-friendly language. Highlight any abnormal values and explain what they mean simply. List any medications and their purpose. Note any follow-up actions. End with: ⚠️ This analysis is generated by an AI assistant and is not a substitute for professional medical advice.";

      const visionMessages: any[] = [
        {
          role: "user",
          content: [
            { type: "text", text: extractionPrompt },
            { type: "image_url", image_url: { url: finalImageUrl } }
          ]
        }
      ];

      const completion = await groq.chat.completions.create({
        messages: visionMessages,
        model: "meta-llama/llama-4-scout-17b-16e-instruct", 
        temperature: 0.5,
        max_tokens: 1024
      });

      res.status(200).json({ reply: completion.choices[0]?.message?.content || "Sorry, I could not generate a response for this image." });
      return;
    }

    // TEXT-ONLY ROUTING
    // If no image is provided, use the fast Groq Llama 3 API
    const messages: any[] = [
      { role: 'system', content: SYSTEM_INSTRUCTION }
    ];

    if (history && Array.isArray(history)) {
      history.forEach((msg: any) => {
        messages.push({
          role: msg.sender === 'user' ? 'user' : 'assistant',
          content: msg.text || "(User uploaded an image here)" 
        });
      });
    }

    messages.push({ role: 'user', content: message });

    const completion = await groq.chat.completions.create({
      messages,
      model: "llama-3.1-8b-instant", 
      temperature: 0.5,
    });

    const responseText = completion.choices[0]?.message?.content || "Sorry, I could not generate a response.";
    res.status(200).json({ reply: responseText });

  } catch (error: any) {
    console.error('AI Processing Error:', error);
    res.status(500).json({ message: 'Failed to process chat with HealthAI', error: error.message });
  }
};
